### ISSUE TITLE
Atomic features

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#12]
Hi,

Is there a way to get access to the atomic features after fitting a potential? l mean is there a simple way to use the python functions with in the code to input an atomic configuration (a unit cell or a super cell) and output the features that are calculated for each atom based on a fitted potential (basically based on the number of N body terms used in the potential and fitted values for the radial basis)?

I'm trying an active learning/sampling method and I rather use the features that are being used in the ACE, than using a different featurization.

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
Please check this example: 
https://github.com/ICAMS/python-ace/blob/master/examples/pyace/bbasis_projections.ipynb

However, for active learning we already have some functionality based on MaxVol algorithm (similar to MTP potentials), that will be publicly available in a few weeks

**Comment by siamak-attarian** [comment]
Thank you so much!
