### ISSUE TITLE
Magnetization and charge transfer

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#13]
Hello,

I was wondering if there is any plan to include properties like magnetization or charge transfer based on the paper

"Atomic cluster expansion of scalar, vectorial, and tensorial properties including magnetism and charge transfer"

in near future, to the current ACE code.

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
Hi, there are some plans, but they are  mid- or long-terms
