### ISSUE TITLE
How to use 'number_of_functions_per_element' from the python interface

### ISSUE THREAD

**Issue by pmrv** [ICAMS/python-ace#17]
I'm calculating the ACE descriptors with the ASE calculator as in the [example](https://github.com/ICAMS/python-ace/blob/master/examples/pyace/bbasis_projections.ipynb) with `pyace.create_multispecies_basis_config`.

This is my potential config
```python
pot_conf =  {
    'deltaSplineBins': 0.001,
    'elements': ['Al', 'Mg'],

    'embeddings': {'ALL': {'drho_core_cut': 250,
                           'fs_parameters': [1, 1],
                           'ndensity': 1,
                           'npot': 'FinnisSinclair',
                           'rho_core_cut': 200000},
                  },

    'bonds': {'ALL': {'NameOfCutoffFunction': 'cos',
                      'core-repulsion': [10000.0, 5.0],
                      'dcut': 0.01,
                      'radbase': 'ChebPow',
                      'radparameters': [2.0],
                      'rcut': 6},
             },
                   
    'functions': {'ALL': {
            'nradmax_by_orders': [10, 2, 2, 1],
            'lmax_by_orders':    [0,  1, 2, 1]
        }
    }
}
```
This works, but now I'd like to use the new 'number_of_functions_per_element' feature.  I've tried

1. to add it to the functions block, but it seems to be ignored,
2. to replace the contents of the `['functions']['ALL']` block with `{'number_of_functions_per_element': 200}`. This gives an error that `nradmax` and `lmax` are not defined.

Grepping the source I find mentions of it only in the `generalfit` module and the pacemaker script.  Is it not yet available from the python interface?

**Comment by yury-lysogorskiy** [comment]
I refactored the code, so this logic now is moved into pyace.create_multispecies_basis_config in https://github.com/ICAMS/python-ace/tree/feature/refactor-number-of-function-per-element
Please, be aware, that you should provide BOTH:
1) potential shape, i.e. nradmax_per_order, etc. (but you could use very large defaults) 
2)  'number_of_functions_per_element': 200 

See example below:
```python

pot_conf =  {
    'deltaSplineBins': 0.001,
    'elements': ['Al', 'Mg'],

    'embeddings': {'ALL': {'drho_core_cut': 250,
                           'fs_parameters': [1, 1],
                           'ndensity': 1,
                           'npot': 'FinnisSinclair',
                           'rho_core_cut': 200000},
                  },

    'bonds': {'ALL': {'NameOfCutoffFunction': 'cos',
                      'core-repulsion': [10000.0, 5.0],
                      'dcut': 0.01,
                      'radbase': 'ChebPow',
                      'radparameters': [2.0],
                      'rcut': 6},
             },
                   
    'functions': {
      'number_of_functions_per_element': 200,
      'UNARY':   { 'nradmax_by_orders': [ 15, 6, 4, 3, 2, 2 ], 'lmax_by_orders': [ 0 , 3, 3, 2, 2, 1 ]},
      'BINARY':  { 'nradmax_by_orders': [ 15, 6, 3, 2, 2, 1 ], 'lmax_by_orders': [ 0 , 3, 2, 1, 1, 0 ]},
      'ALL':     { 'nradmax_by_orders': [ 15, 3, 2, 1, 1 ],    'lmax_by_orders': [ 0 , 2, 2, 1, 1 ] }
    }
}
```

Please let me know, if this is doing what you expected

**Comment by pmrv** [comment]
Hey @yury-lysogorskiy, I just got to pick this project up again. I see that you merged the branch already, so I just wanted to say, it's working great, thank you!

**Comment by yury-lysogorskiy** [comment]
Thank you @pmrv , with that I will close this issue
