### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by leiapple** [ICAMS/python-ace#23]
Hi,

I have successfully installed pyace following the instructions (without any warning). But I encountered the 'Segmentation fault (core dumped)' error when I was using pacemaker. I have used the precious version of pyace and it works well. Have you ever encountered such a problem? 

Kind regards,

Lei

**Comment by leiapple** [comment]
Just to adds up: after installation, pace_timing, pace_info etc. are working except pacemaker.

**Comment by yury-lysogorskiy** [comment]
Hi!  we need more details about it. Could you provide log files or screen output, plese ?

**Comment by leiapple** [comment]
Hi Yury,

Thanks for the swift reply. 

There is not much output actually. I only got "Segmentation fault" when I run "pacemaker -t" in the terminal. But when I run pace_info and pace_timing for a potential that I trained before. It is working well. 

I am wondering if this would be a compatibility issue with the library or packages. I am using conda to manage the environment.
My python version is Python 3.8.15.
The package versions are 
------------------
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.3.0                    pypi_0    pypi
ase                       3.22.1                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2022.10.11           h06a4308_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libclang                  14.0.6                   pypi_0    pypi
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
matplotlib                3.6.2                    pypi_0    pypi
maxvolpy                  0.3.8                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
numpy                     1.23.5                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0
pyace                     0.2.7+67.g898ac7c          pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0
sqlite                    3.40.0               h5082296_0
tensorboard               2.8.0                    pypi_0    pypi
tensorflow                2.8.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.28.0                   pypi_0    pypi
tf-estimator-nightly      2.8.0.dev2021122109          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                h5eee18b_0
zlib                      1.2.13               h5eee18b_0
------------------

Kind regards,

Lei

**Comment by leiapple** [comment]
Hi Yury,

Thanks for the swift reply.

There is not much output, actually. I only got `Segmentation fault` when I run `pacemaker -t` in the terminal. But when I run `pace_info` and `pace_timing` for a potential that I trained before. It is working well.

I am wondering if this would be a compatibility issue with the library or packages. I am using conda to manage the environment.
My python version is Python 3.8.15.
The package versions are
-------------------
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.3.0                    pypi_0    pypi
ase                       3.22.1                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2022.10.11           h06a4308_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libclang                  14.0.6                   pypi_0    pypi
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
matplotlib                3.6.2                    pypi_0    pypi
maxvolpy                  0.3.8                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
numpy                     1.23.5                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0
pyace                     0.2.7+67.g898ac7c          pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0
sqlite                    3.40.0               h5082296_0
tensorboard               2.8.0                    pypi_0    pypi
tensorflow                2.8.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.28.0                   pypi_0    pypi
tf-estimator-nightly      2.8.0.dev2021122109          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                h5eee18b_0
zlib                      1.2.13               h5eee18b_0
-------------------


Kind regards,

Lei

**Comment by leiapple** [comment]
Hi Yury,

Thanks for the swift reply.

There is not much output, actually. I only got Segmentation fault when I run pacemaker -t in the terminal. But when I run pace_info and pace_timing for a potential that I trained before. It is working well. I am wondering if this would be a compatibility issue with the library or packages. I am using conda to manage the environment.
My python version is Python 3.8.15.

The package versions are
`-------------------
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.3.0                    pypi_0    pypi
ase                       3.22.1                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2022.10.11           h06a4308_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libclang                  14.0.6                   pypi_0    pypi
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
matplotlib                3.6.2                    pypi_0    pypi
maxvolpy                  0.3.8                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
numpy                     1.23.5                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0
pyace                     0.2.7+67.g898ac7c          pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0
sqlite                    3.40.0               h5082296_0
tensorboard               2.8.0                    pypi_0    pypi
tensorflow                2.8.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.28.0                   pypi_0    pypi
tf-estimator-nightly      2.8.0.dev2021122109          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                h5eee18b_0
zlib                      1.2.13               h5eee18b_0
-------------------`

Kind regard,

Lei

**Comment by leiapple** [comment]
Sorry for the bad format. This should look better.

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.3.0                    pypi_0    pypi
ase                       3.22.1                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2022.10.11           h06a4308_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libclang                  14.0.6                   pypi_0    pypi
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
matplotlib                3.6.2                    pypi_0    pypi
maxvolpy                  0.3.8                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
numpy                     1.23.5                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0
pyace                     0.2.7+67.g898ac7c          pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0
sqlite                    3.40.0               h5082296_0
tensorboard               2.8.0                    pypi_0    pypi
tensorflow                2.8.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.28.0                   pypi_0    pypi
tf-estimator-nightly      2.8.0.dev2021122109          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                h5eee18b_0
zlib                      1.2.13               h5eee18b_0

**Comment by yury-lysogorskiy** [comment]
If you just run python and try import pyace, would that work ?
```
$ python
>> import pyace
>> from pyace import *
```

**Comment by yury-lysogorskiy** [comment]
Mhm, then it is something related to python/conda env, and not to pyace/pacemaker. Probably due to inconsistency between environments?
Check `which python`, check that it points to python inside the conda environment that you created

**Comment by leiapple** [comment]
Ye I see... 

Thanks for the help!
