### ISSUE TITLE
How can the L-BFGS-B history be increased?

### ISSUE THREAD

**Issue by mikejwaters** [ICAMS/python-ace#25]
Hi,  When using pacemaker with BFGS, the fully dense hessian seems to be making fitting iterations take ~3x longer than If I use L-BFGS-B.  It looks like the powerful GPUs we have are waiting on the CPUs to solve the update step with BFGS. However, L-BFGS-B has much slower convergence with respect to number of iterations.  I suspect the poor convergence is due to the L-BGFS-B memory length being only 10 iterations be default (m=10 in the second link).   

Is there a way I can pass a longer history parameter to the optimizer? 

https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b

**Comment by yury-lysogorskiy** [comment]
Hi!
Please, check the "options" in "fit" section of `input.yaml`
https://pacemaker.readthedocs.io/en/latest/pacemaker/inputfile/#fitting_settings
In L-BFGS-B case, you need to provide:
```yaml
fit:
 #...
 optimizer: L-BFGS-B
 options: {maxcor: 100} 
 #...
```

**Comment by mikejwaters** [comment]
Thanks @yury-lysogorskiy ! I should have seen that on my own.  Once I get my next paper out, I'll have some more interesting technical questions for you.

**Comment by mikejwaters** [comment]
Happy New Year!

I was wondering if the `maxls` (maximum number of line search steps) can be tuned from the default of 20 to improve fitting performance. Has anyone explored this? I've lowered it to 5 without any stability issues. 

Best,
-Mike

**Comment by yury-lysogorskiy** [comment]
Thank you, happy New Year too!

I think yes, please feel free to tune any optimizer parameters if you see any gain. Usually we use BFGS instead of L-BFGS-B, which has no  this parameter `maxls` .
