### ISSUE TITLE
Radial Regularization Documentation

### ISSUE THREAD

**Issue by mikejwaters** [ICAMS/python-ace#26]
Hi, 

Is there documentation somewhere on how the radial regularization works? 

From reading the source code, I assume that w0_rad,  w1_rad, and w2_rad are weights for derivative orders. Is there a more explicit description?

Best,
-Mike

**Comment by yury-lysogorskiy** [comment]
Hi!
Yes, you can find most of the details in the paper "Efficient parametrization of the atomic cluster expansion", PRM 6, 013804 (2022). Here is paragraph about radial smoothness regularization:
![image](https://user-images.githubusercontent.com/22479612/216280335-edb2feb0-8d7f-474d-b7b1-e719e7ad9e36.png)

**Comment by mikejwaters** [comment]
Great thanks!  I like how the penalty weights short distances higher to match the naturally large forces. Maybe this could be added to the documentation for the next release?
