### ISSUE TITLE
Windows install pyace problem

### ISSUE THREAD

**Issue by jhung12** [ICAMS/python-ace#27]
Hi

I got a problem when running pip install upgrade 

      **CMake Error at CMakeLists.txt:5 (project):
        Generator

          Visual Studio 15 2017 Win64

        does not support platform specification, but platform

          x64

        was specified.**

I got visual studio 2022 version, but I am not sure how to ask for it

**Comment by yury-lysogorskiy** [comment]
Hi! Currently we do not support windows installation. But it may change in the future
