### ISSUE TITLE
Extracting the ACE descriptors out of PyACE

### ISSUE THREAD

**Issue by zakmachachi** [ICAMS/python-ace#36]
Dear developers, 

I was wondering if is possible to extract the ACE vectors separately as one can do with the julia implementation. My understanding is pacemaker is used for fitting but it would be a nice feature to extract and visualise the ACE vectors (UMAP, PCA, etc) before fitting to see the data shape.

**Comment by yury-lysogorskiy** [comment]
Yes, check this example: https://github.com/ICAMS/python-ace/blob/master/examples/pyace/bbasis_projections.ipynb

**Comment by zakmachachi** [comment]
Thanks for the example, I see you can extract the vectors out which is nice. Is it not possible to do this without fitting a potential?

**Comment by yury-lysogorskiy** [comment]
@zakmachachi you also can use non-fitted (i.e. no radial function being optimized) potential, aka "from scratch", just check the same [example](https://github.com/ICAMS/python-ace/blob/master/examples/pyace/bbasis_projections.ipynb) , second part
