### ISSUE TITLE
Error installing pyace

### ISSUE THREAD

**Issue by amirbehbahanian** [ICAMS/python-ace#4]
Hi, I followed the installation procedure for ACE and with python 3.8, Cmake 3.22.4, TensorFlow 2.5, and after the installation of Tensorpotential during the installation of python-ace using `pip install --upgrade .` I get the following error I would appreciate your comment on the problem.

```
Building wheels for collected packages: pyace
  Building wheel for pyace (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /sw/eb/sw/Anaconda3/2021.05/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2wumzvxw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2wumzvxw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1funyjpu
       cwd: /tmp/pip-req-build-2wumzvxw/
  Complete output (158 lines):
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/radial.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/asecalc.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/atomicenvironment.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/generalfit.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/lossfuncspec.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/pyneighbor.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/__init__.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/validate.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/paralleldataexecutor.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/preparedata.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/read_base_conf.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/metrics_aggregator.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/_version.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/fitadapter.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/multispecies_basisextension.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/const.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/pyacefit.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/basisextension.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/helpers.py -> build/lib.linux-x86_64-3.8/pyace
  copying src/pyace/fitcallbacks.py -> build/lib.linux-x86_64-3.8/pyace
  creating build/lib.linux-x86_64-3.8/pyace/ace
  copying src/pyace/ace/__init__.py -> build/lib.linux-x86_64-3.8/pyace/ace
  creating build/lib.linux-x86_64-3.8/pyace/utils
  copying src/pyace/utils/__init__.py -> build/lib.linux-x86_64-3.8/pyace/utils
  copying src/pyace/utils/timing.py -> build/lib.linux-x86_64-3.8/pyace/utils
  creating build/lib.linux-x86_64-3.8/pyace/data
  copying src/pyace/data/__init__.py -> build/lib.linux-x86_64-3.8/pyace/data
  copying src/pyace/data/mus_ns_uni_to_rawlsLS_np_rank.pckl -> build/lib.linux-x86_64-3.8/pyace/data
  copying src/pyace/data/input_template.yaml -> build/lib.linux-x86_64-3.8/pyace/data
  UPDATING build/lib.linux-x86_64-3.8/pyace/_version.py
  set build/lib.linux-x86_64-3.8/pyace/_version.py to '0.2.7+36.gbfc87d7'
  running build_ext
  Compilation configuration:  Release
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/g++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /sw/eb/sw/Anaconda3/2021.05/bin/python (found version "3.8.8")
  -- Found PythonLibs: /sw/eb/sw/Anaconda3/2021.05/lib/libpython3.8.so
  -- pybind11 v2.3.dev0
  EVALUATOR_PATH=/tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator
  EVALUATOR_PATH=/tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-2wumzvxw/build/temp.linux-x86_64-3.8
  Building arguments:  -- -j sharmonics
  [ 33%] Building CXX object CMakeFiles/sharmonics.dir/lib/ace/src/fitting/ace_spherical_polar.cpp.o
  [ 66%] Building CXX object CMakeFiles/sharmonics.dir/lib/ace/src/fitting/ace_couplings.cpp.o
  [ 66%] Building CXX object CMakeFiles/sharmonics.dir/src/pyace/ace/ace_spherical_polar_binding.cpp.o
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_arraynd.h:38:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:6,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h: In constructor ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = double]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h:57:5: error: conversion from ‘const char [6]’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
       ContiguousArrayND() = default;
       ^
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:7:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h: In constructor ‘Array2DLM<T>::Array2DLM() [with T = double]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h:64:5: note: synthesized method ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = double]’ first required here
       Array2DLM() = default;
       ^
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp: In constructor ‘ACESHarmonics::ACESHarmonics(LS_TYPE)’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:15:40: note: synthesized method ‘Array2DLM<T>::Array2DLM() [with T = double]’ first required here
   ACESHarmonics::ACESHarmonics(LS_TYPE lm) {
                                          ^
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_arraynd.h:38:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:6,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h: In constructor ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = ACEComplex]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h:57:5: error: conversion from ‘const char [6]’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
       ContiguousArrayND() = default;
       ^
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:7:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h: In constructor ‘Array2DLM<T>::Array2DLM() [with T = ACEComplex]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h:64:5: note: synthesized method ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = ACEComplex]’ first required here
       Array2DLM() = default;
       ^
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp: In constructor ‘ACESHarmonics::ACESHarmonics(LS_TYPE)’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:15:40: note: synthesized method ‘Array2DLM<T>::Array2DLM() [with T = ACEComplex]’ first required here
   ACESHarmonics::ACESHarmonics(LS_TYPE lm) {
                                          ^
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_arraynd.h:38:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:6,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h: In constructor ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = ACEDYcomponent]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_contigous_array.h:57:5: error: conversion from ‘const char [6]’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
       ContiguousArrayND() = default;
       ^
  In file included from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.h:7:0,
                   from /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:4:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h: In constructor ‘Array2DLM<T>::Array2DLM() [with T = ACEDYcomponent]’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/ace-evaluator/src/ace_array2dlm.h:64:5: note: synthesized method ‘ContiguousArrayND<T>::ContiguousArrayND() [with T = ACEDYcomponent]’ first required here
       Array2DLM() = default;
       ^
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp: In constructor ‘ACESHarmonics::ACESHarmonics(LS_TYPE)’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_spherical_polar.cpp:15:40: note: synthesized method ‘Array2DLM<T>::Array2DLM() [with T = ACEDYcomponent]’ first required here
   ACESHarmonics::ACESHarmonics(LS_TYPE lm) {
                                          ^
  gmake[3]: *** [CMakeFiles/sharmonics.dir/lib/ace/src/fitting/ace_spherical_polar.cpp.o] Error 1
  gmake[3]: *** Waiting for unfinished jobs....
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_couplings.cpp: In function ‘int generate_basis_function_n_body(RANK_TYPE, const NS_TYPE*, const LS_TYPE*, const LS_TYPE*, ACEBBasisFunction&, const ACEClebschGordan&, bool)’:
  /tmp/pip-req-build-2wumzvxw/lib/ace/src/fitting/ace_couplings.cpp:370:52: warning: non-constant array size in new, unable to verify length of initializer-list [enabled by default]
       b_basis_function.mus = new SPECIES_TYPE[rank]{0};
                                                      ^
  gmake[2]: *** [CMakeFiles/sharmonics.dir/all] Error 2
  gmake[1]: *** [CMakeFiles/sharmonics.dir/rule] Error 2
  gmake: *** [sharmonics] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-2wumzvxw/setup.py", line 109, in <module>
      setup(
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-2wumzvxw/versioneer.py", line 1791, in run
      _build_ext.run(self)
    File "/tmp/pip-req-build-2wumzvxw/setup.py", line 39, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-2wumzvxw/setup.py", line 86, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args,
    File "/sw/eb/sw/Anaconda3/2021.05/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--', '-j', 'sharmonics']' returned non-zero exit status 2.
  ----------------------------------------
```

**Comment by yury-lysogorskiy** [comment]
Hi! it seems that you are using old C++ compiler (GNU 4.8.5) that does not support C++11 standard by default. I tried to configure it in CMakeLists.txt, but I would recommend to use newer C++ compiler

**Comment by braxtonowens** [comment]
Hello, I am getting a similar error. I ran "pip install cmake" however this did not fix the issue. 

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0jnqkuft/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0jnqkuft/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vi4outg6/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/cbo27/.local/include/python3.8/pyace
         cwd: /tmp/pip-req-build-0jnqkuft/
    Complete output (84 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/asecalc.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/pyneighbor.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/radial.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/preparedata.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/fitcallbacks.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/pyacefit.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/generalfit.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/basisextension.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/multispecies_basisextension.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/atomicenvironment.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/__init__.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/metrics_aggregator.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/fitadapter.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/paralleldataexecutor.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/read_base_conf.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/validate.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/const.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/helpers.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/_version.py -> build/lib.linux-x86_64-3.8/pyace
    copying src/pyace/lossfuncspec.py -> build/lib.linux-x86_64-3.8/pyace
    creating build/lib.linux-x86_64-3.8/pyace/data
    copying src/pyace/data/__init__.py -> build/lib.linux-x86_64-3.8/pyace/data
    creating build/lib.linux-x86_64-3.8/pyace/utils
    copying src/pyace/utils/__init__.py -> build/lib.linux-x86_64-3.8/pyace/utils
    copying src/pyace/utils/timing.py -> build/lib.linux-x86_64-3.8/pyace/utils
    creating build/lib.linux-x86_64-3.8/pyace/ace
    copying src/pyace/ace/__init__.py -> build/lib.linux-x86_64-3.8/pyace/ace
    copying src/pyace/data/mus_ns_uni_to_rawlsLS_np_rank.pckl -> build/lib.linux-x86_64-3.8/pyace/data
    copying src/pyace/data/input_template.yaml -> build/lib.linux-x86_64-3.8/pyace/data
    UPDATING build/lib.linux-x86_64-3.8/pyace/_version.py
    set build/lib.linux-x86_64-3.8/pyace/_version.py to '0.2.7+45.gbbe5dfc'
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-req-build-0jnqkuft/setup.py", line 26, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0jnqkuft/setup.py", line 110, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-0jnqkuft/versioneer.py", line 1791, in run
        _build_ext.run(self)
      File "/tmp/pip-req-build-0jnqkuft/setup.py", line 28, in run
        raise RuntimeError(
    RuntimeError: CMake must be installed to build the following extensions: pyace/sharmonics, pyace/coupling, pyace/basis, pyace/evaluator, pyace/catomicenvironment, pyace/calculator
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0jnqkuft/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0jnqkuft/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vi4outg6/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/cbo27/.local/include/python3.8/pyace Check the logs for full command output.

**Comment by yury-lysogorskiy** [comment]
you should another installation scenarios for `cmake` rather than `pip install`:
*  install/update cmake with linux-based tools, i.e. `apt` or `snap`  for Ubuntu: `sudo apt-get install cmake`
or
*  Install cmake with [conda](https://anaconda.org/anaconda/cmake) `conda install -c anaconda cmake`
