### ISSUE TITLE
computing Basis functions

### ISSUE THREAD

**Issue by zfan2016** [ICAMS/python-ace#41]
Can we use pacemaker to compute Basis functions B_iv and A_iv for each atom in an atomic configuration?

**Comment by yury-lysogorskiy** [comment]
For B_iv - yes, by using the underlying python interface. Check this: https://pacemaker.readthedocs.io/en/latest/pacemaker/faq/#how_to_compute_b-basis_projections_for_various_structures
for A_iv - no, they are not extracted, since they are not rotationally invariant anyway
