### ISSUE TITLE
Some questions about some parameters in input.yaml::potential

### ISSUE THREAD

**Issue by zfan2016** [ICAMS/python-ace#47]
For bond section in input.yaml::potential, could explain which parameters in the equations of your 2022 PRM paper correspond to radparameters, rcut and dcut in input.yaml?
What is the relation between the two parameters, rcut and cutoff, in input.yaml? 
When change cutoff, should one also change the values for radparameters, rcut and dcut?

What does UNARY mean for embedding, bonds and functions? For embedding, what is the difference between UNARY and single element, e.g. Al or Ni? 

If I have trained AB.yaml and AC.yaml for the two single two-element salts AB and AC (in the training/test dataset, the composition is always 50:50 for a single salt), respectively, and then would like to train an ABC.yaml works well for binary mixture AB_x-AC_(1-x), (x is in the range of b/t 0 and 1), 
I guess:
in the upfitting: I don't need to specify anything for embedding; for bonds I just need to specify BC; for functions, I just need to specify (B, C) and TERNARY.
is it right? 

Next, if I have trained ABC.yaml, ABD.yaml and BCD.yaml for the three binary salt mixtures, AB-AC, AB-AD and AC-AD, respectively,  and then would like to train an ABCD.yaml for any ternary mixture AB_x-AC_y-AD_(1-x-y), 
I feel: 
in the upfitting: I don't need to specify anything for embedding and bonds, and I just need to specify QUATERNARY, is it correct?

For core repulsion, I know from your 2022 PRM paper that the repulsion is solely controlled by \rho_core or the equation C11 when r < r_in - \Delta_in. But what is the core repulsion when r_in - \Delta_in < r < r_in ?

**Comment by jhung12** [comment]
in the paper you mention
rcut is in equation C8
and dcut is in C10 

looking at eq C2,  radial basis function is your choice of radial basis function and cutoff function. cutoff function exists to make sure its local and its smooth at boundary. see Fig12

cutoff is when you first start the project but rcut can override it.

**Comment by jhung12** [comment]
radparameter is lambda in C6 and C4

you may be confused about the equations.
cut off function is defined as C9 which is a function of dct(delta) and rcut(r_c) in C10

**Comment by zfan2016** [comment]
Got it. Thanks. 

Could you explain what UNARY means for embedding, bonds and functions?

**Comment by jhung12** [comment]
Unary just means you only have one element for your training data.
embedding is the function of energy see eq 3
and functions refers to B5 and C1

**Comment by zfan2016** [comment]
I see. Thanks. 

May I know what is the core repulsion when r_in - \Delta_in < r < r_in ?

And could you confirm if my thoughts regarding training potentials for binary/ternary salts after training potentials for unary two-element / binary salts is correct or not?

**Comment by yury-lysogorskiy** [comment]
@jhung12  thank you for answering! 

@zfan2016 Just small adds-up:
- in the region  r_in - \Delta_in < r < r_in there is smooth switching from ACE to core-repulsion
- UNARY, BINARY, ..., ALL are just syntactic sugar keywords, and they internally automatically expand to all possible (symmetrically relevant) combinations of elements.
-- embeddings are defined per central atom types, i.e. UNARY is enough
-- bonds are defined per unordered atom-pair, so for two elements A and B, UNARY=A-A and B-B, BINARY=A-B and B-A
-- functions are defined for all possible ordered subset of elements and they are organized by species blocks in the final potential, i.e. UNARY=A,B BINARY=A-B,B-A, TERNARY=A-B-C,B-A-C,C-A-B (if third element C is presented), etc.
- when you add-up previously fitted potential and want to up-fit new interaction, usually you have just to define these new interactions, like specified [here](https://pacemaker.readthedocs.io/en/latest/pacemaker/faq/#how_to_fit_only_certain_part_of_the_potential_ie_binary_interaction_only)

However, this is not very common and tested scenario of fitting ACE with pacemaker, so, please feel free to report any issues if you would find them

**Comment by zfan2016** [comment]
Thank you for the answers!

**Comment by zfan2016** [comment]
Hello, when I conducted upfitting, the error below alway came up. Could you give me some suggestions to resolve it?

Traceback (most recent call last):
  File "/global/homes/z/zfan/.conda/envs/ace/bin/pacemaker", line 438, in <module>
    main(sys.argv[1:])
  File "/global/homes/z/zfan/.conda/envs/ace/bin/pacemaker", line 279, in main
    general_fit = GeneralACEFit(potential_config=potential_config, fit_config=fit_config, data_config=data_config,
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/generalfit.py", line 197, in __init__
    self.target_bbasisconfig = construct_bbasisconfiguration(potential_config,
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/basisextension.py", line 73, in construct_bbasisconfiguration
    return create_multispecies_basis_config(potential_config, initial_basisconfig=initial_basisconfig,
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/multispecies_basisextension.py", line 344, in create_multispecies_basis_config
    blocks_list = create_multispecies_basisblocks_list(potential_config,
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/multispecies_basisextension.py", line 625, in create_multispecies_basisblocks_list
    blocks_specifications_dict = generate_blocks_specifications_dict(potential_config)
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/multispecies_basisextension.py", line 472, in generate_blocks_specifications_dict
    bonds_ext = update_bonds_ext(bonds_ext, functions_ext)
  File "/global/homes/z/zfan/.conda/envs/ace/lib/python3.8/site-packages/pyace/multispecies_basisextension.py", line 592, in update_bonds_ext
    bond = bonds_ext[bkey]
KeyError: ('F', 'Li')
