### ISSUE TITLE
AssertionError: Energy weights sum differs from one and equal to 0.75

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#5]
Hi,

I'm training couple of data sets from the same pool of data. for some of them I get:

 File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/preparedata.py", line 826, in generate_
weights
    assert np.allclose(energy_weights_sum, 1), "Energy weights sum differs from one and equal to {}".format(
AssertionError: Energy weights sum differs from one and equal to 0.75

what causes this? is it something about my data?

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
which  weighting policy is being used?  in `input.yaml` , `fit` section, try to comment out `weighting` subsection completely.

**Comment by siamak-attarian** [comment]
The default weighting that is with in the template. I'll try playing with the possible weighting options.
Thank you
