### ISSUE TITLE
Issues when running LAMMPS with ACE

### ISSUE THREAD

**Issue by YuanbinLiu** [ICAMS/python-ace#51]
Hi authors, do you have any ideas about this issue when running LAMMPS with ACE? 

LAMMPS (23 Jun 2022 - Update 3)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  triclinic box = (0 0 0) to (328.73874 46.989717 81.388576) with tilt (0 0 -1.82e-08)
  32 by 4 by 5 MPI processor grid
  reading atoms ...
  119328 atoms
  read_data CPU = 0.506 seconds
ACE version: 2021.10.25
Recursive evaluator is used
Loading ./aln_gb_ver4.yace
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'

**Comment by jhung12** [comment]
what is your input for lammps

**Comment by yury-lysogorskiy** [comment]
seems that format of YACE file is not valid
