### ISSUE TITLE
Large Force Errors

### ISSUE THREAD

**Issue by tarbaugh** [ICAMS/python-ace#53]
Thank you for sharing this code, it is a very nice package. 

I have however been running into an issue, which I have not been able to solve. I have a dataset of perturbed crystal and liquid configurations, (~10k crystal environments, ~10k liquid) made up of well-converged DFT calculations for a binary alloy. I have noticed that, although the crystal configurations train very well, any addition of the liquid configurations causes the forces to go haywire. This includes training on just the liquid configurations, and results in a parity plot with a nearly vertical line as shown below. The wide range of predicted forces tells me that this not just a poor fit, or noisy data, but rather something going wrong in preparation of the dataset or training. I have been testing all aspects of preparation (QE+ASE, even with classical force fields!) and training (kappa, potential size, # iterations) and cannot find the cause yet. Only selecting the linear embedding results in any improvement (reduced magnitude of forces).

Has anyone come across a similar situation? I am happy to share any material. Thanks in advance.

<img width="589" alt="Forces" src="https://github.com/ICAMS/python-ace/assets/66973128/f94b8995-82af-45bf-be0b-5d7678964d32">

**Comment by yury-lysogorskiy** [comment]
could you, please, share the train_ef_distribution.png file from the same folder where you run pacemaker and the log.txt files

**Comment by tarbaugh** [comment]
Here is the most recent attempt, again resulting in a similar parity plot.

![train_ef-distributions](https://github.com/ICAMS/python-ace/assets/66973128/c2568441-604f-4ac1-8aed-9a9b4ebf0bd6)

**Comment by yury-lysogorskiy** [comment]
you energies are not corrected. `energy_corrected` - total energy of a structure minus a reference energy of free atoms. It should be cohesive energies. It should be distributed in a narrow ( few eV/atom )energy range and not thousands of eV/atom

**Comment by tarbaugh** [comment]
I wil do this, thank you.

**Comment by tarbaugh** [comment]
I can confirm this was the cause of the issues - thank you!
