### ISSUE TITLE
specifying embedding-function for PyACECalculator

### ISSUE THREAD

**Issue by OliverYL** [ICAMS/python-ace#56]
Dear developers,

I used the PyACECalculator as an ASE calculator to calculate the energy but met **"Notice! No embedding-function is specified, but potential has linear embedding, default embedding-function: FinnisSinclair would be assumed"**

The ACE potential for Silicon is from npj Computational Materials (2021)7:97 (https://doi.org/10.1038/s41524-021-00559-9) and the calculation code is as follows:

````
from pyace import *
from ase.io import read

calc = PyACECalculator("Si_npj_CompMat2021.ace")

atoms = read('POSCAR.mp-149_Si')
````

Is it possible to use the potential shared by npj Computational Materials (2021)7:97 correctly via ASE calculator like the form mentioned here? Maybe by specifying the embedding-function? 

Thanks~

Lei

**Comment by yury-lysogorskiy** [comment]
It is just info message to adopt old format of potential file. Potential usage should not be affected
