### ISSUE TITLE
YAML safe_load has been removed

### ISSUE THREAD

**Issue by ale99WGiais** [ICAMS/python-ace#60]
Hi

I just installed python-ace. While trying to use "pacemaker", i encountered the following fatal error:
"AttributeError: safe_load() has been removed" 

My fix was to replace the line with 
"
yaml_loader = yaml.YAML(typ='safe', pure=True)
args_yaml = yaml_loader.load(f)
"
directly in the file "/home/alessio/.conda/envs/ace/bin/pacemaker"

**Comment by ale99WGiais** [comment]
Hey

Here some info that can help you


(ace_gpu) ***@***.*** ~]$ python --version
Python 3.9.18

(ace_gpu) ***@***.*** ~]$ conda list
# packages in environment at /home/alessio/.conda/envs/ace_gpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
_tflow_select             2.1.0                       gpu    anaconda
abseil-cpp                20230802.0           h6a678d5_2    anaconda
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.8.5            py39h5eee18b_0    anaconda
aiosignal                 1.2.0              pyhd3eb1b0_0    anaconda
ase                       3.22.1                   pypi_0    pypi
astor                     0.8.1            py39h06a4308_0    anaconda
astunparse                1.6.3                      py_0    anaconda
async-timeout             4.0.2            py39h06a4308_0    anaconda
attrs                     23.1.0           py39h06a4308_0    anaconda
blas                      1.0                         mkl    anaconda
blinker                   1.6.2            py39h06a4308_0    anaconda
brotli-python             1.0.9            py39h6a678d5_7    anaconda
c-ares                    1.19.1               h5eee18b_0    anaconda
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0    anaconda
certifi                   2023.7.22        py39h06a4308_0    anaconda
cffi                      1.15.1           py39h5eee18b_3    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
click                     8.1.7            py39h06a4308_0    anaconda
contourpy                 1.1.1                    pypi_0    pypi
cryptography              41.0.3           py39hdda0065_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
cupti                     10.1.168                      0    anaconda
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.5                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
fonttools                 4.44.0                   pypi_0    pypi
frozenlist                1.4.0            py39h5eee18b_0    anaconda
gast                      0.3.3                    pypi_0    pypi
google-auth               2.22.0           py39h06a4308_0    anaconda
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0              pyhd3eb1b0_0    anaconda
gputil                    1.4.0              pyh9f0ad1d_0    conda-forge
grpc-cpp                  1.48.2               he1ff14a_3    anaconda
grpcio                    1.32.0                   pypi_0    pypi
gtest                     1.14.0               hdb19cb5_0    anaconda
h5py                      2.10.0           py39hec9cf62_0    anaconda
hdf5                      1.10.6               h3ffc7dd_1    anaconda
idna                      3.4              py39h06a4308_0    anaconda
importlib-metadata        6.0.0            py39h06a4308_0    anaconda
intel-openmp              2023.1.0         hdb19cb5_46305    anaconda
joblib                    1.3.2                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0    anaconda
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libprotobuf               3.20.3               he621ea3_0    anaconda
libstdcxx-ng              11.2.0               h1234567_1
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               14.0.6               h9e868ea_0
markdown                  3.4.1            py39h06a4308_0    anaconda
markupsafe                2.1.1            py39h7f8727e_0    anaconda
matplotlib                3.6.3                    pypi_0    pypi
maxvolpy                  0.3.8                    pypi_0    pypi
micromamba                1.5.1                         1    conda-forge
mkl                       2023.1.0         h213fc3f_46343    anaconda
mkl-service               2.4.0            py39h5eee18b_1    anaconda
mkl_fft                   1.3.8            py39h5eee18b_0    anaconda
mkl_random                1.2.4            py39hdb19cb5_0    anaconda
multidict                 6.0.2            py39h5eee18b_0    anaconda
ncurses                   6.4                  h6a678d5_0
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.2            py39h06a4308_0    anaconda
openssl                   3.1.4                hd590300_0    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1    anaconda
packaging                 23.2                     pypi_0    pypi
pandas                    1.4.4                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3             py39h06a4308_0
protobuf                  3.20.3           py39h6a678d5_0    anaconda
psutil                    5.9.6                    pypi_0    pypi
pyace                     0.2.7+129.g809804b          pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0    anaconda
pyasn1-modules            0.2.8                      py_0    anaconda
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pyjwt                     2.4.0            py39h06a4308_0    anaconda
pyopenssl                 23.2.0           py39h06a4308_0    anaconda
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0    anaconda
python                    3.9.18               h955ad1f_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
re2                       2022.04.01           h295c915_0    anaconda
readline                  8.2                  h5eee18b_0
requests                  2.31.0           py39h06a4308_0    anaconda
requests-oauthlib         1.3.0                      py_0    anaconda
rsa                       4.7.2              pyhd3eb1b0_1    anaconda
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0
six                       1.15.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
tbb                       2021.8.0             hdb19cb5_0    anaconda
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1            py39h06a4308_0    anaconda
tensorflow                2.4.1           gpu_py39h8236f22_0    anaconda
tensorflow-base           2.4.1           gpu_py39h29c2da4_0    anaconda
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-gpu            2.4.1                h30adc30_0    anaconda
tensorpotential           0.2.0+19.gfa5b8b0          pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.18          py39h06a4308_0    anaconda
werkzeug                  2.2.3            py39h06a4308_0    anaconda
wheel                     0.41.2           py39h06a4308_0
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.4.2                h5eee18b_0
yarl                      1.8.1            py39h5eee18b_0    anaconda
zipp                      3.11.0           py39h06a4308_0    anaconda
zlib                      1.2.13               hd590300_5    conda-forge

Il giorno gio 9 nov 2023 alle ore 19:09 yury-lysogorskiy <
***@***.***> ha scritto:

**Comment by yury-lysogorskiy** [comment]
Addressed in Feature/zbl #61
