### ISSUE TITLE
Run PyACECalculator on GPU.

### ISSUE THREAD

**Issue by YangLight** [ICAMS/python-ace#62]
Hi authors! Recently, I've been using the `PyACECalculator` to calculate NVT molecular dynamics and LBFGS relaxation in ASE on cpus, however, the efficiency is not satisfactory since it is serial mode.

So, I wonder if the PyACECalculator can be run on GPU platforms like the
`calculator = MACECalculator(model_path='/content/checkpoints/MACE_model_run-123.model', device='cuda')` ? If it can, how about the gpu efficiency comparing to the single cpu thread?

**Comment by yury-lysogorskiy** [comment]
In contrast to MACE, PyACEcalculator is just a wrapper for standalone serial native C++ implementation, that is used by LAMMPS. IF you really want to run large/long simulations, then I suggest to use LAMMPS.  You can run it on  single CPU core (similar performance to PyACECalculator),  multiple CPUs (using MPI) or one or multiple GPUs, using LAMMPS-KOKKOS. Peformance on A100  <5 microseconds/atom/GPU.

**Comment by YangLight** [comment]
Thank you for your suggestions! So I will turn to LAMMPS on cpus.
