### ISSUE TITLE
Example notebooks missing

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#7]
Hi,

In the documentation of the pacemaker there is a mention of "Notebook" folder which should contain some examples in ipython format, but I can't find it. Has it not been released yet?
I'm looking for:
notebooks/data_custom_weights.ipynb

Just wondering whether it is possible to add different weights to individual atoms, or adding weights to specific atom types.

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
I added this example [here](https://github.com/ICAMS/python-ace/blob/master/examples/custom-weights/data_custom_weights.ipynb)
