### ISSUE TITLE
Maximum number of species ACE can fit in one potential

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#71]
Hello,

I was wondering if there is a "hard coded" limit to the maximum number of species that can be included in one ACE potential in the LAMMPS library of ACE. I'm trying to fit a 12 species system. I tried with different number of elements and realized that after 11 elements, the ACE training would not start and gives the 'Killed' error. With a little manipulation in the "trainable parameters" and eliminating some cross terms between some elements, I successfully fitted and ACE potentials for 12 elements. Now that I try using it in LAMMPS (with the yace format) I get the following error:

Loading output_potential.yace
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

If I selectively take out parameters for a certain set of species and convert them to yace and run the same simulation, it works fine, but when all of them are in the yace file, it gives the above error.

My question is if there is a limit to the number of species that can be included in one ACE potential (in the LAMMPS library of ACE)

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
Practical limit is 6-7 elements, since basis set size grows exponentially. We are planning to release new version of code (gracemaker) in a next few month, without this limitation

**Comment by AdamsGo** [comment]
> Practical limit is 6-7 elements, since basis set size grows exponentially. We are planning to release new version of code (gracemaker) in a next few month, without this limitation
Great news! 
I am trainning a four-element system, the trainning speed is slow. Will gracemaker speed up trainning for multiple-element systems?
@yury-lysogorskiy

**Comment by yury-lysogorskiy** [comment]
Yes, it will, due to usage of Adam optimizer and slightly different model architecture

**Comment by siamak-attarian** [comment]
A few follow-up questions:
Is GRACE it going to be graph neural network based? (hence had to be run on GPUs to be efficient?)
Will there be a version of linear ACE with a reformulated species featurization that would not increase quadratically with the number of species?

**Comment by yury-lysogorskiy** [comment]
We will provide a full series of models: from linear/mild nonlinear single layer with custom C++ implementation in LAMMPS and D-optimality(CPU is enough) to message passing or graph NN that can be executed only with TF but still integrated to LAMMPS(GPU required)
