### ISSUE TITLE
Effectively use D-optimality with existing dataset

### ISSUE THREAD

**Issue by WJiangH** [ICAMS/python-ace#74]
Dear authors,

I am working on training an ACE model to predict specific properties using DFT calculations data. Currently, I have a dataset of approximately 40,000 data points, including ionic steps. Given the large dataset, the training process is notably time-consuming, especially with an increased "number of functions/element". To manage this, I utilized the following command with `pace_collect`:

`pace_select -p target_potential.yaml -o selected_10000.pkl.gz -e "Co Cr Fe Mn Ni" -m 10000 -b 5000 fitting_data_info.pckl.gzip`

Here, `fitting_data_info.pckl.gzip` contains all 40,000 data points. My aim was to select a more representative subset of 10,000 data points. However, I encountered an issue where despite setting "-m 10000", only 729 data points were returned. Training on these 729 data points yields good performance, but the model struggles to predict accurately on the remainder of the dataset (approximately 39,271 points).

Could you suggest an alternative approach or adjustments to better select and utilize the dataset for training?

Thank you for your assistance!

Best regards,
JJ

**Comment by yury-lysogorskiy** [comment]
How large is basis set size of target_potential.yaml? Show log file, if possible

**Comment by WJiangH** [comment]
> How large is basis set size of target_potential.yaml? Show log file, if possible

Here are files. In the input.yaml,  `the number of function/element` is set to 400 and I used command `pace input.yaml --no-fit` to generate the `target_potential.yaml`. 

[input.txt](https://github.com/user-attachments/files/16742013/input.txt)
[target_potential.txt](https://github.com/user-attachments/files/16742016/target_potential.txt)
log file for for dry run: [log.txt](https://github.com/user-attachments/files/16742017/log.txt)
pace_select slrum output: [slurm-2610265.txt](https://github.com/user-attachments/files/16742018/slurm-2610265.txt)

after that, I use `pace_select -p target_potential.yaml -o selected_10000.pkl.gz -e "Co Cr Fe Mn Ni" -m 10000 -b 5000 fitting_data_info.pckl.gzip` to get the dataset.

Is the number of generated data related to the `the number of function/element`? Or I mis-operated something here?

Thank you.
JJ

**Comment by yury-lysogorskiy** [comment]
Thank you for the detailed outputs.

Given 400 functions per element, one can expect MAXIMAL 400 atomic environments selected by MaxVol (because active set is square matrix). So 400 atomic envs * 5 elements = 2000 atomic envs.   
In the extreme case, each atomic environment (i.e. atom) belongs to its own structure. So,  upper limit of number of selected structures is 2000. However it can happen so, that several selected atoms belong to the same structure. 
In your case, these 2000 selected atoms belong to 729 structures only. 

I would suggest, that rest of the structures you can select randomly (unfortunately, you hav to do it manully now).
Load `df=pd.read_pickle("fitting_data_info.pckl.gzip", compression='gzip')`, load `df_sel=pd.read_pickle("selected_10000.pkl.gz")`, drop from df structures with indices as in df_sel, i.e. `df_rest=df.drop(index=df_sel.index)`. Select randomly as much as you wish:
`df_sel2 = df_rest.sample(n=5000, random_state=42)`

P.S.  option `-e "Co Cr Fe Mn Ni"` is used only if you provide structures as LAMMPS dump. For pckl.gzip it has no effect

**Comment by WJiangH** [comment]
> Thank you for the detailed outputs.
> 
> Given 400 functions per element, one can expect MAXIMAL 400 atomic environments selected by MaxVol (because active set is square matrix). So 400 atomic envs * 5 elements = 2000 atomic envs. In the extreme case, each atomic environment (i.e. atom) belongs to its own structure. So, upper limit of number of selected structures is 2000. However it can happen so, that several selected atoms belong to the same structure. In your case, these 2000 selected atoms belong to 729 structures only.
> 
> I would suggest, that rest of the structures you can select randomly (unfortunately, you hav to do it manully now). Load `df=pd.read_pickle("fitting_data_info.pckl.gzip", compression='gzip')`, load `df_sel=pd.read_pickle("selected_10000.pkl.gz")`, drop from df structures with indices as in df_sel, i.e. `df_rest=df.drop(index=df_sel.index)`. Select randomly as much as you wish: `df_sel2 = df_rest.sample(n=5000, random_state=42)`
> 
> P.S. option `-e "Co Cr Fe Mn Ni"` is used only if you provide structures as LAMMPS dump. For pckl.gzip it has no effect

Thank you so much for these detailed explanations for pace_collect!

Just have another quick question that when "ladder fitting" and "early stopping" are used, if "early stopping" is occurred at certain point, e.g., early stopping at total num of func = 800 while the eventual total atomic env = 2000, does it means that even if I directly use atomic env = 2000 without ladder fitting, it is unlikely to give a better performance than that using 800? 

Thank you!
JJ

**Comment by yury-lysogorskiy** [comment]
If I understood you right, you question if whether early stopping means that adding more functions will not improve model further.
No, it does not mean so. I did not test ladder scheme + early stopping (as far as I remember), but I would assume that if you encounter early stopping at given ladder, then it is reasonable to add more functions, i.e. next ladder step...
