### ISSUE TITLE
CPU parallelization

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#8]
Hi,

Is it possible to use CPU parallelization for training with TensorPotential? I think my potential fitting session uses only 1 core. 

Also, is parallelization possible when using PyACECalculator?

Thanks,
Siamak

**Comment by yury-lysogorskiy** [comment]
Hi! 
1) `TensorPotential` is based on the `tensorflow`, which in its turn, try first to find GPU and corresponding libraries.  If it is not succeed, then it switch to the CPU executor as default. See also here: https://pacemaker.readthedocs.io/en/latest/pacemaker/faq/#i_dont_have_a_gpu_should_i_use_backend_evaluator_tensorpotential_or_pyace
You could also run `pacemaker` with `--verbose-tf` option to see more detailed log of `tensorflow`

If you have no GPU or you configured it to use CPU explicitly, it should use all cores automatically. It doesn't mean that CPU usage will be 100% all the time, but should reach 100% only at peak calculations.

If you want to set the number of CPU cores to be used by TF, try to use following environment variables:
```
export OMP_NUM_THREADS=5
export TF_NUM_INTRAOP_THREADS=5
export TF_NUM_INTEROP_THREADS=5
```
(from [here](https://stackoverflow.com/a/68967461))

2) PyACECalculator is executed only in serial mode. If you need to run larger systems/longer simulations, you could use LAMMPS with all its MPI parallelization included
