### ISSUE TITLE
Question about uncertainty indication methods

### ISSUE THREAD

**Issue by psn417** [ICAMS/python-ace#82]
Dear author:

In the ACE paper [Physical Review B 99, 014104 (2019)], it is mentioned that there are two types of trainable parameters:

1. parameters in linear expansion (E = c_1 B_1 + c_2 B_2 + ....)
2. parameters in radial basis function (R(r) = c_1 g_1(r) + c_2 g_2(r) + ...)

In the MTP paper [Computational Materials Science 156, 148 (2019)], both types of parameters seem to be used in the computation of the B matrix.

However, in your paper [Physical Review Materials 7, 043801 (2023)], it appears that only type-1 parameters are used in constructing the B matrix, both in the linear and non-linear cases.

Could you clarify why type-2 parameters are not used for the B matrix construction?

Thank you for your time and clarification.

**Comment by yury-lysogorskiy** [comment]
Due to computational efficiency, we assume they are fixed. This is not strictly valid assumption, but pratically it works.

**Comment by psn417** [comment]
Thank you very much for your reply! I understand now. I will close the issue.
